### ISSUE TITLE
Installing tools via API causes failure to load tools

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10651]
I am calling `POST /api/tool_shed_repositories/install_repository_revision` numerous times to install repositories individually.
`/api/tool_shed_repositories` lists the repository as installed, `/api/tools` does not list the tools that the repository is supposed to have installed. Restarting the server does not resolve the issue. The shed_tool_conf does not list the missing tools, while the tools xml wrappers are present in their toolshed install directory. The repositories with missing tools is different every time I reinstall, with a varying number of missing tools. I expect there is a race condition while writing to the shed_tool_conf.xml file.

Galaxy 20.09 with delay_tool_initialization: true

**Comment by mvdbeek** [comment]
Can you post the logs ?

**Comment by innovate-invent** [comment]
[logs-from-galaxy-app-in-galaxy-app-f5f579c-kdq2h.txt](https://github.com/galaxyproject/galaxy/files/5505222/logs-from-galaxy-app-in-galaxy-app-f5f579c-kdq2h.txt)

**Comment by martenson** [comment]
fixed via https://github.com/galaxyproject/galaxy/pull/10655

**Comment by innovate-invent** [comment]
I updated Galaxy and reran a test. The repositories install properly, and list the tools in the tool box but workflows can't find the tool:
```
galaxy.jobs.handler DEBUG 2020-11-11 21:40:14,044 Grabbed WorkflowInvocation(s): 41
galaxy.workflow.scheduling_manager DEBUG 2020-11-11 21:40:14,050 Attempting to schedule workflow invocation [(41,)]
galaxy.workflow.modules WARNING 2020-11-11 21:40:14,120 The tool 'toolshed.g2.bx.psu.edu/repos/brinkmanlab/awkscript/awkscript/1.0' is missing. Cannot build workflow module.
galaxy.workflow.run ERROR 2020-11-11 21:40:14,120 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 83, in __invoke
    outputs = invoker.invoke()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 174, in invoke
    remaining_steps = self.progress.remaining_steps()
  File "/srv/galaxy/lib/galaxy/workflow/run.py", line 306, in remaining_steps
    self.module_injector.inject(step, step_args=self.param_map.get(step.id, {}))
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1973, in inject
    module.add_dummy_datasets(connections=step.input_connections, steps=steps)
  File "/srv/galaxy/lib/galaxy/workflow/modules.py", line 1530, in add_dummy_datasets
    raise ToolMissingException("Tool %s missing. Cannot add dummy datasets." % self.tool_id,
galaxy.exceptions.ToolMissingException: Tool toolshed.g2.bx.psu.edu/repos/brinkmanlab/awkscript/awkscript/1.0 missing. Cannot add dummy datasets.
galaxy.workflow.scheduling_manager DEBUG 2020-11-11 21:40:14,137 Workflow invocation [41] scheduled
```

I confirmed that manually running this tool outside of a workflow works. Even manually rerunning the tool after failure in the workflow succeeds. I have tried invoking the workflow a few times and I still get the same failure.

**Comment by mvdbeek** [comment]
The problem seems to stem from installing tools in parallel. That's not what the install process is designed for, so I don't think there's much we can do in the short run. Note that all the auxiliary scripts in the ecosystem that install tools try hard to avoid installing in parallel.
