### ISSUE TITLE
tool form help conversion produces conflicting IDs causing rendering problems

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1839]
it seems

```
Background
----------------------
```

is converted to 

```
<div class="section" id="background">
```

which then renders as 

https://test.galaxyproject.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_plot_fingerprint/deeptools_plot_fingerprint/2.1.0.0

![screenshot 2016-03-02 12 52 38](https://cloud.githubusercontent.com/assets/1814954/13469509/a7bfdb3e-e075-11e5-8367-0ea42ff38c90.png)

the IDs purpose after the conversion is probably to provide #anchor - but we do not need nor use that so we should be free to just remove all IDs after the conversion

**Comment by bgruening** [comment]
@martenson actually 

```
Background
----------------
```

is converted to this css tag. @guerler said he needs to prefix the header to avoid this. We fixed it in the latest release by changing the header to `technical background`

**Comment by martenson** [comment]
@bgruening I would not consider that a fix, rather a workaround. We should still fix it properly by either not doing it or removing it afterwards.

**Comment by bgruening** [comment]
Sure, sure, but we would like to have it on 16.01 and 15.10 :)

**Comment by hexylena** [comment]
Based on the test URL, it looks fixed :)

**Comment by martenson** [comment]
@erasche this is not fixed, I suspect you can face it again at any time when you stumble upon the conflicting names
