### ISSUE TITLE
17.05 Release Review Meeting

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3866]
We need to have a release meeting, we should do it early to try to have an on-time release. The initial potential date and time with 4 👍 s is ~~April 14th at 11am EST~~

**Comment by martenson** [comment]
👍

**Comment by martenson** [comment]
Due to Scientific Advisory Board meeting preparations this is now in conflict with our internal meeting. It would be best if we could postpone the Release Review Meeting to the next week. 

Hopefully this will also enable the Galaxy Team to be all in one room for this review.

Date to be proposed early next week. Sorry @galaxyproject/core for the late notice.

**Comment by martenson** [comment]
Is ~~9.30am EST on Friday~~ a good time for you? @bgruening @mvdbeek @erasche @nsoranzo ?

**Comment by mvdbeek** [comment]
I can't promise anything for this week, we've got another evaluation Monday and Tuesday.

**Comment by hexylena** [comment]
yeah, that's fine for me.

**Comment by nsoranzo** [comment]
I'm giving a workshop on Friday, sorry, no time till next week for me.

**Comment by martenson** [comment]
We will push this to the next week then. We want more than 50% people if possible. :) What day can you do folks?

**Comment by hexylena** [comment]
any time other than tuesday or thursday.

**Comment by nsoranzo** [comment]
Any time next week.

**Comment by martenson** [comment]
What about [11am EST Wednesday 4/26](https://www.timeanddate.com/worldclock/fixedtime.html?month=04&day=26&year=2017&hour=11&min=0&sec=0&p1=43) ?

Ping @galaxyproject/core

**Comment by dannon** [comment]
Sure.

**Comment by nekrut** [comment]
I have two priorities which we need to make every effort to include into release:

- history tags #3730. They are fine in their current implementation as on test site with one exception: the requirement to type `name:` before the tag. As discussed with @dannon during team meeting this can be replaced with a single symbol such as `#`
- Jupyter dataset bug #3974 is an absolutely killer showstopper for new users, and should be fixed as the IE paper has been officially accepted today (Apr 25)

**Comment by dannon** [comment]
@nekrut Yep, the hashtag stuff will be in this week.

**Comment by jmchilton** [comment]
I previously +1'd that time - but I guess I'd rather delay the release meeting until after all the required enhancements for 17.05 are merged.

**Comment by dannon** [comment]
@jmchilton Seems like it might be a good plan to still have the meeting at the proposed time, make sure these are our only two outstanding 'required enhancements', and then freeze on Friday?

**Comment by martenson** [comment]
I am with Dannon here. We have all European committers available and set -
let's discuss what needs to be done and go through the milestone in GitHub.

M.

**Comment by jmchilton** [comment]
Fine with being out voted here - seems there is still a quorum.
