### ISSUE TITLE
Toolshed Installed tool : Job submission Failed after upgrading galaxy to 17.05

### ISSUE THREAD

**Issue by juliechevalier** [galaxyproject/galaxy#4591]
Issue temporarly resolved with help of other user (https://biostar.usegalaxy.org/p/24710/#24766)
Some tools (in my case only bedtools and deeptools, but not samtools for example) installed in my previous version of galaxy with toolshed, fail to run in the new version of galaxy.
The formular is available, but when we execute the job, no entry appears in history and a red pop-up appears with this message :

{
"tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_intersectbed/2.24.0",
"tool_version": "2.24.0",
"inputs": {
    "inputA": {
        "values": [
            {
                "hid": 72,
                "id": "be2dfb734c2d1ff7",
                "keep": false,
                "name": "convert_",
                "src": "hda",
                "tags": []
            }
        ],
        "batch": false
    },
    "inputB": {
        "values": [
            {
                "hid": 72,
                "id": "be2dfb734c2d1ff7",
                "keep": false,
                "name": "convert_",
                "src": "hda",
                "tags": []
            }
        ],
        "batch": false
    },
    "strand": "",
    "overlap_mode": [
        "-wa"
    ],
    "split": "false",
    "fraction": "",
    "reciprocal": "false",
    "invert": "false",
    "once": "false",
    "count": "false",
    "header": "false"
}
uninstall and reinstall these tools doesn't resolve the problem
resolved by removing "guid=..." in config/shed_tool_conf.xml

**Comment by mvdbeek** [comment]
Hello @juliechevalier, please do not edit the `shed_tool_conf.xml` file, this will break the tool lineage and repository updates. Can you check which commit of the 17.05 release you are using? We had some similar reports previously that should have been fixed with https://github.com/galaxyproject/galaxy/commit/368be188d0918adaa0d7f752883c24bb79f261ec.

**Comment by juliechevalier** [comment]
Hello,
To be sure, I have reupdated my galaxy and withe command git log I obtain this :
commit cfabe37d69549e919d3fce15cbcca108fdcf1597
Merge: 5d7b524 706a5b2
Author: Nate Coraor <nate@bx.psu.edu>
Date:   Thu Sep 21 15:26:24 2017 -0400

    Merge branch 'release_17.01' into release_17.05

I retest toolshed installed tools without modify the guid, with and without the line "AllowEncodedSlashes NoDecode" in the apache config file.

But the bug persists.
Thanks for your help.
Julie

**Comment by mvdbeek** [comment]
Have you cleared the browser cache ? Can you open the javascript console and see if there are any errors ? IS there a traceback in the logs ?

**Comment by juliechevalier** [comment]
As you mentionned in http://dev.list.galaxyproject.org/Toolshed-partial-installation-deeptools-error-td4671098.html , I have modified my galaxy.ini to set `preserve_python_environment= legacy` and I'm working with the original shed_tool_conf.xml without manual modification.
I've cleared the browser cache
I've restarted galaxy.
SO, the pop-up error is still the same that mentionned in the begin of this issue.
In javascript console (I suppose it is obtained by right click on page and choosing "inspect element"), I obtain this message :
"JQMIGRATE: Migrate is installed with logging active, version 1.4.0" libs.bundled.js:44:478
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ libs.bundled.js:26:0
"JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8" libs.bundled.js:44:116
console.trace(): libs.bundled.js:44
n() libs.bundled.js:44
t.attr() libs.bundled.js:44
zt() libs.bundled.js:24
.attr() libs.bundled.js:25
s</p<.render() analysis.bundled.js:1
y() libs.bundled.js:27
v() libs.bundled.js:27
d() libs.bundled.js:27
c.trigger() libs.bundled.js:27
.set() libs.bundled.js:27
s</<.render() analysis.bundled.js:5
s</<.initialize() analysis.bundled.js:5
e.View() libs.bundled.js:27
$/n<() libs.bundled.js:27
s</d<._addRow() analysis.bundled.js:5
s</d<.add() analysis.bundled.js:5
s</d<.render/<() analysis.bundled.js:5
_.forEach() libs.bundled.js:26
s</d<.render() analysis.bundled.js:5
s</d<.initialize() analysis.bundled.js:5
e.View() libs.bundled.js:27
$/n<() libs.bundled.js:27
s</d<._addConditional() analysis.bundled.js:5
s</d<.add() analysis.bundled.js:5
s</d<.render/<() analysis.bundled.js:5
_.forEach() libs.bundled.js:26
s</d<.render() analysis.bundled.js:5
s</d<.initialize() analysis.bundled.js:5
e.View() libs.bundled.js:27
$/n<() libs.bundled.js:27
s</<._renderForm() analysis.bundled.js:2
s</<.render() analysis.bundled.js:2
s</<._buildForm() analysis.bundled.js:6
s</<._buildModel/<.success() analysis.bundled.js:6
h/<.success() libs.bundled.js:27
d/<() libs.bundled.js:27
vt.Callbacks/l() libs.bundled.js:24
vt.Callbacks/c.fireWith() libs.bundled.js:24
n() libs.bundled.js:26
.send/e()

And in log file I obtain this :

**Comment by juliechevalier** [comment]
log file content :
`192.168.100.150 - - [03/oct./2017:12:28:13 +0200] "GET /galaxy/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_compute_matrix/deeptools_compute_matrix/2.5.1.1.0/build?tool_version=2.5.1.1.0 HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/admin_toolshed/static/images/a0d84b45643a2678/computeMatrix_selectScores.png HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/admin_toolshed/static/images/a0d84b45643a2678/computeMatrix_advancedOutput.png HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/admin_toolshed/static/images/a0d84b45643a2678/computeMatrix_output.png HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/admin_toolshed/static/images/a0d84b45643a2678/computeMatrix_selectRegions.png HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/admin_toolshed/static/images/a0d84b45643a2678/computeMatrix_overview.png HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_compute_matrix/deeptools_compute_matrix/2.5.1.1.0/citations HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fadmin_toolshed%2Fstatic%2Fimages%2Fa0d84b45643a2678%2FcomputeMatrix_selectRegions.png HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fadmin_toolshed%2Fstatic%2Fimages%2Fa0d84b45643a2678%2FcomputeMatrix_overview.png HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fadmin_toolshed%2Fstatic%2Fimages%2Fa0d84b45643a2678%2FcomputeMatrix_selectScores.png HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fadmin_toolshed%2Fstatic%2Fimages%2Fa0d84b45643a2678%2FcomputeMatrix_output.png HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:28:15 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fadmin_toolshed%2Fstatic%2Fimages%2Fa0d84b45643a2678%2FcomputeMatrix_advancedOutput.png HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"

192.168.100.150 - - [03/oct./2017:12:30:23 +0200] "POST /galaxy/api/tools HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
192.168.100.150 - - [03/oct./2017:12:30:23 +0200] "GET /galaxy/root/login?redirect=%2Fgalaxy%2Fapi%2Ftools HTTP/1.1" 200 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"
galaxy.queue_worker DEBUG 2017-10-03 12:30:26,794 Executing toolbox reload on 'main'`

**Comment by mvdbeek** [comment]
> 192.168.100.150 - - [03/oct./2017:12:30:23 +0200] "POST /galaxy/api/tools HTTP/1.1" 302 - "http://192.168.100.98:8080/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fdeeptools_compute_matrix%2Fdeeptools_compute_matrix%2F2.5.1.1.0&version=2.5.1.1.0&__identifer=cd26f0wv7eh" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0"

So here you're getting a 302 redirect ... that is probably the issue (perhaps in conjunction with galaxy being served under a subdirectory)

**Comment by mvdbeek** [comment]
Can you post apache2 rewrite rules and the version of apache2 that you are using ?

**Comment by juliechevalier** [comment]
My apache 2 version is : 
Server version: Apache/2.4.18 (Ubuntu)

My apache2 rewrite rules are here:

	AllowEncodedSlashes NoDecode

	RewriteEngine on
	RewriteRule ^/galaxy$ /galaxy/ [R]
	RewriteRule ^/galaxy/static/style/(.*) /data/galaxy-dist/static/june_2007_style/blue/$1 [L]
	RewriteRule ^/galaxy/static/scripts/(.*) /data/galaxy-dist/static/scripts/packed/$1 [L]
	RewriteRule ^/galaxy/static/(.*) /data/galaxy-dist/static/$1 [L]
	RewriteRule ^/galaxy/favicon.ico /data/galaxy-dist/static/favicon.ico [L]
	RewriteRule ^/galaxy/robots.txt /data/galaxy-dist/static/robots.txt [L]
	RewriteRule ^/galaxy(.*) http://localhost:8080$1 [P]
