### ISSUE TITLE
Trim whitespace in URL upload box?

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#8196]
If there is a leading whitespace in the data upload form, the files won't upload. From the user perspective, seems like a whitespace trim would be an acceptable automatic operation to perform by the UI?

![Screen Shot 2019-06-19 at 1 41 25 PM](https://user-images.githubusercontent.com/338642/59790929-03a34d80-929f-11e9-8e58-1fd659790d69.png)

**Comment by martenson** [comment]
This is definitely a bug, I think we fixed it in the past but maybe it resurfaced.

**Comment by jdavcs** [comment]
The blank line above the edited if-statement is unintentional. If this solution works, I'll remove it.

**Comment by afgane** [comment]
This bug has resurfaced:
![image](https://user-images.githubusercontent.com/338642/72851176-ee4d3200-3c78-11ea-88fd-7c7b6e5109e0.png)

This is on 20.01.

**Comment by martenson** [comment]
@ic4f are you still up for solving this? I am unclear about why #8197 was closed.

**Comment by ic4f** [comment]
@martenson absolutely! I believe there was a security issue involved that was taken care of separately.  I think @nsoranzo brought it up (sorry if I'm mistaken - it was almost a year ago, so I may be forgetting stuff). Since the whitespace is not resolved, yes, sure, I'll take care of it. However, I'm off until next Thursday, so I'll get to it week after next.
