### ISSUE TITLE
Default tool data tables are not loaded

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#8534]
According to current tool_data_table.conf.xml.sample (https://github.com/galaxyproject/galaxy/blame/dev/lib/galaxy/config/sample/tool_data_table_conf.xml.sample):
```
<!-- Paths are relative to the value of `tool_data_path` in galaxy.ini -->
```

However, when each of the `<file path="asdf.loc" />` are parsed, the files are not loaded. Changing back to `<file path="tool-data/asdf.loc" />` causes the (sample) location files to be loaded as they should. Seen on a fresh dev checkout.

Most likely occurred around (merging of) #921

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/8484

**Comment by natefoo** [comment]
#8610 should fix this.

**Comment by martenson** [comment]
Has this been fixed @blankenberg @natefoo ?

**Comment by mvdbeek** [comment]
This is not fixed yet.

**Comment by jdavcs** [comment]
I can take a look (could be that the path is not resolved correctly in some scenarios), but I need a little help/pointers. What would be a good way to test this/recreate this behavior? (i.e., are those files loaded for particular tools?)

**Comment by mvdbeek** [comment]
`class ToolDataPathFiles` looks brokenish, not your fault, I think I got it.

**Comment by jdavcs** [comment]
OK, sounds good.

**Comment by mvdbeek** [comment]
ugh, we have a nice mix in there:
```
<!-- Paths are relative to the value of `tool_data_path` in galaxy.ini -->
<tables>
    <!-- Locations of all fasta files under genome directory -->
    <table name="all_fasta" comment_char="#" allow_duplicate_entries="False">
        <columns>value, dbkey, name, path</columns>
        <file path="all_fasta.loc" />
    </table>
    <!-- Locations of indexes in the BFAST mapper format -->
    <table name="bfast_indexes" comment_char="#" allow_duplicate_entries="False">
        <columns>value, dbkey, formats, name, path</columns>
        <file path="bfast_indexes.loc" />
    </table>
    <!-- Locations of nucleotide BLAST databases -->
    <table name="blastdb" comment_char="#" allow_duplicate_entries="False">
        <columns>value, name, path</columns>
        <file path="tool-data/blastdb.loc" />
    </table>
    <!-- Locations of protein BLAST databases -->
    <table name="blastdb_p" comment_char="#" allow_duplicate_entries="False">
        <columns>value, name, path</columns>
        <file path="blastdb_p.loc" />
    </table>
```

not sure what to do there. In principle the `tool-data` entries are not quite right. But all this guessing of paths is ... a bit painful.

**Comment by mvdbeek** [comment]
Should be fixed with https://github.com/galaxyproject/galaxy/pull/8942
